const IngredientData = {
  ingredients: [
    'Carrot',
    'Potato',
    'Sweet Potato',
    'Onion',
    'Red Onion',
    'Garlic',
    'Shallot',
    'Broccoli',
    'Cauliflower',
    'Spinach',
    'Zucchini',
    'Yellow Squash',
    'Butternut Squash',
    'Pumpkin',
    'Asparagus',
    'Kale',
    'Arugula',
    'Fennel',
    'Okra',
    'Celery',
    'Beetroot',
    'Artichoke',
    'Brussels Sprouts',
    'Bell Pepper (Red)',
    'Bell Pepper (Green)',
    'Bell Pepper (Yellow)',
    'Eggplant',
    'Cabbage',
    'Napa Cabbage',
    'Bok Choy',
    'Swiss Chard',
    'Turnip',
    'Radish',
    'Leek',
    'Green Beans',
    'Snow Peas',
    'Sweet Corn',
    'Peas',
    'Watercress',
    'Endive',
    'Mushroom (Button)',
    'Mushroom (Shiitake)',
    'Mushroom (Portobello)',
    'Mushroom (Oyster)',
    'Mushroom (Enoki)',
    'Apple (Red)',
    'Apple (Green)',
    'Banana',
    'Orange',
    'Mango',
    'Papaya',
    'Kiwi',
    'Strawberry',
    'Raspberry',
    'Blueberry',
    'Blackberry',
    'Cranberry',
    'Pineapple',
    'Pomegranate',
    'Grapefruit',
    'Lemon',
    'Lime',
    'Fig',
    'Guava',
    'Pear',
    'Lychee',
    'Apricot',
    'Peach',
    'Nectarine',
    'Plum',
    'Cherry',
    'Watermelon',
    'Cantaloupe',
    'Honeydew Melon',
    'Dragon Fruit',
    'Passion Fruit',
    'Star Fruit',
    'Persimmon',
    'Coconut',
    'Date',
    'Prunes',
    'Chicken Breast',
    'Chicken Thigh',
    'Ground Chicken',
    'Beef Steak',
    'Ground Beef',
    'Pork Chop',
    'Pork Belly',
    'Lamb Chops',
    'Veal Cutlet',
    'Duck Breast',
    'Turkey Breast',
    'Quail',
    'Goose',
    'Salmon Fillet',
    'Tuna (Canned)',
    'Tuna (Fresh)',
    'Cod',
    'Shrimp',
    'Crab',
    'Lobster',
    'Scallops',
    'Mussels',
    'Clams',
    'Oysters',
    'Sardines',
    'Anchovies',
    'Eggs',
    'Tofu',
    'Tempeh',
    'Seitan',
    'Lentils (Green)',
    'Lentils (Red)',
    'Chickpeas',
    'Black Beans',
    'Pinto Beans',
    'Kidney Beans',
    'Rice (White)',
    'Rice (Brown)',
    'Jasmine Rice',
    'Basmati Rice',
    'Quinoa',
    'Couscous',
    'Barley',
    'Farro',
    'Millet',
    'Buckwheat',
    'Polenta',
    'Cornmeal',
    'Oats (Rolled)',
    'Oats (Steel-Cut)',
    'Bulgur',
    'Orzo',
    'Wheat Berries',
    'Amaranth',
    'Almonds',
    'Cashews',
    'Walnuts',
    'Pistachios',
    'Peanuts',
    'Hazelnuts',
    'Brazil Nuts',
    'Macadamia Nuts',
    'Pine Nuts',
    'Chia Seeds',
    'Flaxseeds',
    'Sunflower Seeds',
    'Pumpkin Seeds',
    'Poppy Seeds',
    'Sesame Seeds',
    'Hemp Seeds',
    'Black Pepper',
    'White Pepper',
    'Salt',
    'Paprika',
    'Smoked Paprika',
    'Cayenne Pepper',
    'Cumin',
    'Coriander',
    'Turmeric',
    'Ginger (Fresh)',
    'Ginger (Powder)',
    'Garlic Powder',
    'Onion Powder',
    'Saffron',
    'Cardamom',
    'Cloves',
    'Star Anise',
    'Bay Leaves',
    'Thyme',
    'Oregano',
    'Basil',
    'Parsley',
    'Cilantro',
    'Dill',
    'Rosemary',
    'Sage',
    'Tarragon',
    'Chervil',
    'Marjoram',
    'Mint',
    'Fennel Seeds',
    'Caraway Seeds',
    'Mustard Seeds',
    'Fenugreek',
    'Sumac',
    'Olive Oil',
    'Extra Virgin Olive Oil',
    'Canola Oil',
    'Vegetable Oil',
    'Sunflower Oil',
    'Grapeseed Oil',
    'Avocado Oil',
    'Sesame Oil',
    'Coconut Oil',
    'Peanut Oil',
    'Balsamic Vinegar',
    'White Vinegar',
    'Apple Cider Vinegar',
    'Red Wine Vinegar',
    'Rice Vinegar',
    'Malt Vinegar',
    'Milk (Whole)',
    'Milk (Skim)',
    'Milk (Almond)',
    'Cream (Heavy)',
    'Cream (Whipping)',
    'Butter',
    'Ghee',
    'Yogurt (Plain)',
    'Yogurt (Greek)',
    'Cheese (Cheddar)',
    'Cheese (Mozzarella)',
    'Cheese (Parmesan)',
    'Cheese (Feta)',
    'Cheese (Blue)',
    'Cheese (Ricotta)',
    'Cottage Cheese',
    'Cream Cheese',
    'Soy Sauce',
    'Fish Sauce',
    'Hoisin Sauce',
    'Worcestershire Sauce',
    'Ketchup',
    'Mayonnaise',
    'Mustard (Yellow)',
    'Mustard (Dijon)',
    'BBQ Sauce',
    'Hot Sauce',
    'Tahini',
    'Teriyaki Sauce'
  ]
}

export default IngredientData
